apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: circuit-breaker-for-service-bff
  namespace: default
spec:
  host: service-bff
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 15s
      maxEjectionPercent: 100
